const mongoose = require("mongoose");
const dotenv = require("dotenv");
const colors = require("colors");
const connectDB = require("./config/db");

// Load Models
const Order = require("./models/orderModel");
const Product = require("./models/productModel");
const User = require("./models/userModel");

dotenv.config();

connectDB();

const seedOrders = async () => {
  try {
    // 1. Get necessary data
    // We need existing products to link them to orders
    const products = await Product.find({});
    if (products.length === 0) {
      console.error("Error: No products found. Please run regular seeder first.".red.inverse);
      process.exit(1);
    }

    // We need a user to assign orders to (optional, but good for testing myorders)
    // We'll try to find a customer, otherwise use any user
    let user = await User.findOne({ role: "customer" });
    if (!user) {
      user = await User.findOne({});
    }

    if (!user) {
      console.error("Error: No users found. Please run regular seeder first.".red.inverse);
      process.exit(1);
    }

    console.log(`Seeding orders for user: ${user.name} (${user.email})`.cyan);

    // 2. Clear existing orders (Optional: comment out if you want to Append)
    // await Order.deleteMany(); 
    // console.log("Existing orders cleared...".red);

    const orders = [];
    const governorates = ["Cairo", "Giza", "Alexandria", "Mansoura", "Luxor"];
    const statuses = ["Pending", "Processing", "Shipped", "Delivered", "Cancelled"];

    // 3. Generate 20 Orders
    for (let i = 0; i < 20; i++) {
        // Pick random product
        const product = products[Math.floor(Math.random() * products.length)];
        
        // Pick random variant from that product
        const variant = product.variants && product.variants.length > 0 
            ? product.variants[Math.floor(Math.random() * product.variants.length)]
            : { size: "M", color: "Black" }; // Fallback

        const qty = Math.floor(Math.random() * 3) + 1; // 1 to 3 items
        const price = product.price;
        const total = price * qty;
        
        const randomStatus = statuses[Math.floor(Math.random() * statuses.length)];
        
        // Determine realistic dates based on status
        const createdAt = new Date();
        createdAt.setDate(createdAt.getDate() - Math.floor(Math.random() * 30)); // Past 30 days
        
        let deliveredAt = null;
        if (randomStatus === "Delivered") {
            deliveredAt = new Date(createdAt);
            deliveredAt.setDate(deliveredAt.getDate() + 3); // Delivered 3 days later
        }

        const order = {
            user: user._id,
            orderItems: [
                {
                    name: product.name,
                    qty: qty,
                    image: product.coverImage,
                    price: price,
                    product: product._id,
                    size: variant.size,
                    color: variant.color
                }
            ],
            shippingAddress: {
                fullName: user.name,
                address: `${Math.floor(Math.random() * 900) + 100} Street Name St.`,
                city: "Test City",
                governorate: governorates[Math.floor(Math.random() * governorates.length)],
                phoneNumber: "01000000000"
            },
            paymentMethod: "COD",
            itemsPrice: total,
            shippingPrice: 50,
            totalPrice: total + 50,
            isPaid: randomStatus === "Delivered", // Assume paid if delivered for simplicity
            paidAt: randomStatus === "Delivered" ? deliveredAt : null,
            isDelivered: randomStatus === "Delivered",
            deliveredAt: deliveredAt,
            status: randomStatus,
            // order_id will be auto-generated by the model hook!
            
            // Override timestamps to simulate history
            createdAt: createdAt, 
            updatedAt: createdAt
        };
        
        orders.push(order);
    }

    // Insert orders one by one to trigger the pre-save hook for order_id
    // insertMany validates but might skip pre-save hooks depending on version, 
    // allow triggering the hook is safer for custom logic like unique ID generation.
    // However, for Mongoose 5.x+, insertMany CAN trigger hooks if configured, 
    // but iterating is 100% safe for our custom ID logic.
    
    console.log("Generating orders...".yellow);
    
    for (const orderData of orders) {
        const order = new Order(orderData);
        await order.save(); // This triggers the pre('save') hook to generate order_id
    }

    console.log("20 Orders Imported Successfully!".green.inverse);
    process.exit();

  } catch (error) {
    console.error(`${error}`.red.inverse);
    process.exit(1);
  }
};

seedOrders();
